name: Deploy React App
on:
  push:
    branches:
      - master
    #paths-ignore:
    #  - '.github/workflows/*'
jobs:
  test: 
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Cash deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
  lint: 
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Cash deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependecies
        run: npm ci
      - name: Lint application
        run: npm run test
  build:
    needs: [lint, test]
    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: $ {{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cash deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependecies
        run: npm ci
      - name: Built application
        run: npm run build
      - name: Deploy
        run: echo Deploying ...