name: Deploy React App
on: push
jobs:
  test: 
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Lint application
        run: npm run test
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Built application
        run: npm run build
      - name: Deploy
        run: echo Deploying ...

      