name: Test React App
on: push
jobs:
  test: 
    runs-on: ubuntu-22.04
    steps:
      - name: Get rep code
        uses: actions/chekout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test

      